install.packages("rgeos",repos="http://cran.us.r-project.org")
install.packages("rgdal", repos='http://cran.us.r-project.org',configure.args = c("--with-proj-include=/usr/local/apps/proj/gcc483-4.9.3/include","--with-proj-lib=/usr/local/apps/proj/gcc483-4.9.3/lib" )) 
install.packages("spatialEco",repos="http://cran.us.r-project.org")
install.packages("sp",repos="http://cran.us.r-project.org")
install.packages("usedist",repos="http://cran.us.r-project.org")
install.packages("raster",repos="http://cran.us.r-project.org")
install.packages("spatstat",repos="http://cran.us.r-project.org")
install.packages("igraph",repos="http://cran.us.r-project.org")
install.packages("sf",repos="http://cran.us.r-project.org")
install.packages("rgdal",repos="http://cran.us.r-project.org")
install.packages("gdistance",repos="http://cran.us.r-project.org")
install.packages("otuSummary",repos="http://cran.us.r-project.org")
install.packages("gdata",repos="http://cran.us.r-project.org")
install.packages("maptools",repos="http://cran.us.r-project.org")
install.packages("tidyverse",repos="http://cran.us.r-project.org")
install.packages("reshape2",repos="http://cran.us.r-project.org")
install.packages("data.table",repos="http://cran.us.r-project.org")
require(spatialEco)
require(sp)
require(usedist)
require(rgeos)
require(raster)
require(spatstat)
require(igraph)
require(sf)
require(rgdal)
require(gdistance)
require(otuSummary)
require(gdata)
require(maptools)
require(tidyverse)
require(reshape2)
require(data.table)




q()
